Создать структуру задач на основе диаграммы
robot-lab/judyst-backend pull request #10
Opened 2019-03-31 20:48 UTC by levozavr

Для решения задачи создал классы для различных типов задач согласно диаграмме и добавил диаграмму в документацию по проекту

2019-04-01 11:11 UTC, Vasar007 requested changes
Поправь неточности в документе и добавь комментарий для классов задач.

2019-04-01 12:37 UTC, Vasar007 requested changes
Немного исправил формулировку комментария.

2019-04-01 12:37 UTC, Vasar007 commented on tasks/analyzer_task.py
> +    # ToDo: here will be override functions: on_prerun, run, on_success
```suggestion
    # ToDo: here will be overridden functions: on_prerun, run, on_success
```

2019-04-01 12:37 UTC, Vasar007 commented on tasks/core_task.py
> +    # ToDo: here will be override functions: on_prerun, run, on_success
```suggestion
    # ToDo: here will be overridden functions: on_prerun, run, on_success
```

2019-04-01 12:37 UTC, Vasar007 commented on tasks/core_task.py
> +    # ToDo: here will be override functions: on_prerun, run, on_success
```suggestion
    # ToDo: here will be overridden functions: on_prerun, run, on_success
```

2019-04-01 12:37 UTC, Vasar007 commented on tasks/webcrawler_task.py
> +    # ToDo: here will be override functions: on_prerun, run, on_success
```suggestion
    # ToDo: here will be overridden functions: on_prerun, run, on_success
```

2019-04-01 12:37 UTC, Vasar007 commented on tasks/webcrawler_task.py
> +    # ToDo: here will be override functions: on_prerun, run, on_success
```suggestion
    # ToDo: here will be overridden functions: on_prerun, run, on_success
```

2019-04-01 15:23 UTC, levozavr commented
@Vasar007 подправил

2019-04-02 07:32 UTC, Vasar007 approved these changes

2019-04-02 11:01 UTC, danila19991 approved these changes
All ok

2019-04-02 11:51 UTC, merged