Сделать скрипт по заполнению базы данных
robot-lab/judyst-backend pull request #22
Opened 2019-04-05 20:27 UTC by danila19991

Возможности созданного скрипта:
1. Проведение миграции

Closes #18

2019-04-07 13:56 UTC, levozavr commented on init_db.py
> +        print('created', 'DocumentSupertype', name)
А чего не через f-строки?

2019-04-07 13:59 UTC, levozavr commented on init_db.py
> +names_for_check = ['python3.6', 'python3', 'python']
А если в системе нет python 3, но есть python 2, то ты это корректно обрабатывается?

2019-04-07 14:08 UTC, levozavr commented on init_db.py
> +        DocumentSupertype.objects.create(name=name)
тут не рассмотрен такой сценарий: 
- я запустил скрипт заполнил бд
- добавил что-то в конфиг
- запустил скрипт повторно

как результат **ошибка**

2019-04-10 11:19 UTC, Vasar007 reviewed
Хорошо бы прикрутить логирование.

2019-04-10 11:23 UTC, danila19991 commented
@Vasar007 Только позавчера обсуждали с Левой, что на следующий спринт надо взять задачи по настройке логирования и travis

2019-04-10 11:47 UTC, Vasar007 approved these changes
Я бы main ещё распилил на функции, но так тоже нормально.

2019-04-10 17:52 UTC, levozavr commented on README.md
> +    python init_db.py
А может он будет и superuser создавать на основе каких-то значений в environment?

2019-04-10 18:24 UTC, levkovalenko requested changes

2019-04-10 18:24 UTC, levkovalenko commented on init_db_conf.json
> +}
```suggestion
}

```

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +            m = Organisation.objects.get(name=conf['Organisation'])
почему тут не используешь `get_or_create`?

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +        exit(-2)
А коды exit есть в документации, просто я не совсем понимаю разницу между -1 и -2, стоит вынести их в константы которые имеют говорящие названия

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +            conf = json.load(f_in)
предлагаю обратить внимание на [json shema](https://python-jsonschema.readthedocs.io/en/stable/)
это лишь предложение и оно не обязательно к исполнению, возможно это поможет избежать большого количества чеков полей

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +                                conf['AnalyzerType'], show=verbose)
а если у меня в json в поле AnalyzerType в списке один из элементо будет **null** или **number** то нормально произойдет исполнение скрипта?

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +            d = check_fields(elem, ['crawler_name', 'source_link'])
вместо `d` было бы приятнее видеть что-то наподобии `_dict` или `_dictionary`
это опять же лишь предложение и не обязательно к исполнению

2019-04-10 18:24 UTC, levozavr commented on init_db.py
> +def check_fields(old_dict:dict, fields: list)->(None, dict):
а `->(None, dict)` это раюотает как **или** ? или как **и**?
то есть или одно или другое
или же и одно и другое

2019-04-10 22:22 UTC, danila19991 commented on README.md
> +    python init_db.py
@levozavr Предлагаешь подтягивать из переменных среды username, email, password для супер пользователя? Тогда вопрос как это сделать? Я могу создать подтвержденного пользователя через модель пользователя и сделать его superuser, но вызвать создание superuser через manage.py я не смогу.

2019-04-10 22:23 UTC, danila19991 commented on init_db.py
> +            m = Organisation.objects.get(name=conf['Organisation'])
Для создания организации требуется использовать статичный метод create а не objects.create

2019-04-10 22:32 UTC, danila19991 commented
Для проверки полей воспользовался библиотекой trafaret.

2019-04-11 09:03 UTC, levozavr commented on README.md
> +    python init_db.py
можно и так и так, тут особой разницы нет

2019-04-11 09:04 UTC, levozavr commented on init_db.py
> +            m = Organisation.objects.get(name=conf['Organisation'])
а почему?

2019-04-11 09:06 UTC, danila19991 commented on README.md
> +    python init_db.py
не понял

2019-04-11 09:11 UTC, levozavr commented on README.md
> +    python init_db.py
ну ты можешь сделать это и просто ползователя и сделать его superuser

2019-04-11 11:46 UTC, levozavr commented on init_db.py
> +        user = CustomUser.objects.filter(username=username).get()
а что это за старнная конструкция?

2019-04-11 13:10 UTC, levkovalenko approved these changes

2019-04-11 13:11 UTC, levozavr commented
@svkov посмотри пожалуйста PR, ознакомься с ним как будет время

2019-04-17 05:37 UTC, svkov approved these changes
Ознакомился, вроде все ок

2019-04-17 08:41 UTC, merged