Создать структуру репозитория
robot-lab/judyst-backend pull request #4
Opened 2019-03-25 18:29 UTC by levozavr

- [x] создать шаблон django
- [x] настроить celery
- [x] добавить скрипт запуска
- [x] написать генератор настроек
- [x] описать в readme.md способ запуска проекта

close #1

2019-03-26 14:03 UTC, Vasar007 commented
Нету проблем с уязвимостями в Django (используется ли последняя актуальная версия)?

2019-03-26 15:07 UTC, levozavr commented
@Vasar007 я взял последнюю доступную из pip

2019-03-26 15:24 UTC, danila19991 reviewed
Есть несколько вопросов. И хотелось бы увидеть документацию к внутреним функциям celery или внутрение обучение по celery.

2019-03-26 15:24 UTC, danila19991 commented on README.md
> +- manage.py createsuperuser
А нам не нужно запускать gen_settings в предподготовке?

2019-03-26 15:24 UTC, danila19991 commented on start.sh
> +python manage.py migrate
Где генерация local settings?

2019-03-26 15:24 UTC, danila19991 commented on tasks/basic_task.py
> +    pass
Добавь документацию передстартом чего будет выполнятся эта функция.

2019-03-26 17:15 UTC, Vasar007 commented
Во-первых, я, конечно, понимаю, что писать текст, тем более описания, — это не модно, но всё-таки. Можно написать 1–2 предложения, показывающих, для чего создан PR, какие изменения он вносит?  Из контекста и скудного описания issue я предполагаю конечные цели PR, но конечный вариант хотелось бы услышать от самого автора.

Во-вторых, в README стоит указать целевые ОС, на которых можно развернуть систему (ответ, что мол там видно, что написано для Linux, не прокатит, потому что есть много различных дистрибутивов). Вполне достаточно указать предполагаемую систему для запуска (Linux), при этом написав, на каких дистрибутивах проверялась развёртка. Если есть возможность развернуть проект под другие ОС, будет полезным описать кратко данный способ.

Не стоит воспринимать всё это как претензию, ты ведь сам у меня запросил ревью)
Тем более, что я это сейчас пишу дольше, чем всё это можно сделать, да даже ты, @levozavr, вот сейчас читаешь этот текст и то больше времени на это потратишь. Но зато в дальнейшем это упростит возможные проблемы с развёрткой (когда выяснится, что какой-то из пакетов на установленный у меня дистрибутив не портирован, например), а краткое описание PR облегчит жизнь тем, кто собирается тебя ревьювить.

2019-03-26 18:01 UTC, levozavr commented
@Vasar007  Спасибо за комментарии, добавил больше информации в readme, можешь посмотреть?

Так же добавил более полное описание pr, не думал что оно потребуется для этой задачи - инициализации проекта

2019-03-26 18:08 UTC, levozavr commented
@Vasar007  что по поводу approve?

Или есть еще какие-то замечания по коду?

2019-03-26 18:08 UTC, Vasar007 reviewed
Вопрос по SECRET_KEY

2019-03-26 18:08 UTC, Vasar007 commented on judyst_backend/settings.py
> +SECRET_KEY = 'is1*&aohmwn&a3e5(!z*7o49-i%2%1hcwr-nf(tx*p1b&^06u9'
Не нужно ли вынести этот ключ в переменные среды?

2019-03-26 18:11 UTC, levozavr commented on judyst_backend/settings.py
> +SECRET_KEY = 'is1*&aohmwn&a3e5(!z*7o49-i%2%1hcwr-nf(tx*p1b&^06u9'
Упс, согласен

2019-03-26 18:23 UTC, Vasar007 approved these changes
Больше нет замечаний.

2019-03-27 00:00 UTC, danila19991 requested changes
Поправь текст и будет норм.

2019-03-27 00:00 UTC, danila19991 commented on README.md
> +- [Dnjhfz bycnherwbz](https://tecadmin.net/install-rabbitmq-server-debian/)
А что тут написано?

2019-03-27 08:54 UTC, Rexarrior approved these changes

2019-03-27 15:37 UTC, danila19991 approved these changes

2019-03-27 20:40 UTC, merged