Создание документации базы данных
robot-lab/judyst-backend pull request #8
Opened 2019-03-29 11:11 UTC by danila19991

В этом pr доюавляется результат проектрования реляционной базы данных для этого проекта.
- [x] Добвлена схема базы данных с пояснениями в папку documentation.

Closes #2

2019-03-29 14:52 UTC, levkovalenko requested changes
**Общие замечания**
1) по поводу исполнения исполнения отношений, можно их изобразить так: от какого поля к какому идет связь
2) на связях вместо обозначений 0...1 или 0...n обозначать просто 1 или n

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
частным для компании или пользователя?

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +**DocumentOwner** - Отнощение владкльца документа
может стоит упростить модель, что у нас продукт предоставляется организации и документы всех пользователей принадлежат этой организации, а пользователь может быть только в одной организации?

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +3. **raw_data_pk** - Ссылка нв текст который ванализировался(если использовался предобработанный текст)
Опечатки
```suggestion
3. **raw_data_pk** - Ссылка на текст который анализировался(если использовался предобработанный текст)
```

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +**AnalyzeData** - Отнощение использованных анализов
опечатки **отношение**
```suggestion
**AnalyzeData** - Отношение использованных анализов
```

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +4. **analyzer_pk** - Ссылка на тспользованный анализатор
опечатка
```suggestion
4. **analyzer_pk** - Ссылка на использованный анализатор
```

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +5. **doc_pk** - Ссылка на документ еоторому принадлежит свойство
опечатка
```suggestion
5. **doc_pk** - Ссылка на документ которому принадлежит свойство
```

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +**DocumentOwner** - Отнощение владкльца документа
опечатка
```suggestion
**DocumentOwner** - Отношение владельца документа
```

2019-03-29 14:52 UTC, levozavr commented on documentation/database.md
> +3. **organisation_pk** - Ссылка на опгранизацию
Опечатка
```suggestion
3. **organisation_pk** - Ссылка на организацию
```

2019-03-29 15:13 UTC, danila19991 commented
@levozavr не понял 1 пункт, по поводу второго пункта: как тогда отличать 0...1 от 1

2019-03-29 15:14 UTC, danila19991 commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
Предполагалась что документ может быть либо частным либо общедоступным

2019-03-29 15:16 UTC, danila19991 commented on documentation/database.md
> +**DocumentOwner** - Отнощение владкльца документа
это надо всей командой обсудить

2019-03-29 15:25 UTC, levozavr commented on documentation/database.md
> +**DocumentOwner** - Отнощение владкльца документа
Ок

2019-03-29 15:26 UTC, levozavr commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
Частный то есть документ принадлежит  пользователю или компании?

2019-03-29 15:27 UTC, levozavr commented
@danila19991 упс, про 0...1 и  1 уже не актуально
а вот про 0...n и n - актуально

2019-03-29 15:29 UTC, levozavr commented on documentation/database.md
> +**Analyze** - Список всех проведенных анализов
А где у нас результат анализа?

2019-03-29 15:30 UTC, levozavr commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
зачем эта структура?
разве у нас один анализ может проводится на различных позициях в тексте?

2019-03-29 15:33 UTC, danila19991 commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
Под частным подразумевалось что к нему имеют доступ только этот пользователь или пользователи которые состоят в организации, которой принадлежит этот документ

2019-03-29 15:37 UTC, danila19991 commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
Он может проводится на каком-то участке текста или на каком-то тексте, который был получен при помощи какой-то предподготовки

2019-03-29 15:44 UTC, levozavr commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
но у тебя есть возможность что один и тот же анализ производился на разных текстах
![image](https://user-images.githubusercontent.com/30433199/55244679-acb74a80-5252-11e9-86ff-b9e7cd287a54.png)
У тебя отношение что анализы могут повторяться, а не анализ содержит какую-то позицию или raw data

2019-03-29 15:48 UTC, levozavr commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
@danila19991 у тебя тогда получается что только что-то одно для всех документов, так как owner_pk ссылается только на одну таблицу организация или пользователь
Опять же вопрос про то как организовать модель владения документами.

2019-03-29 15:49 UTC, danila19991 commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
Как предлагаешь это исправлять?

2019-03-29 15:51 UTC, levozavr commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
@danila19991 начнем с того что у нас появится в анализе поле analyze_data_pk который будет ссылаться на analyzeData, тогда это будет логичнее

а на мой взгляд самое лучшее решение сделать так:
убрать сущность analyzeData и иметь два public key на RawData и TextPosition

2019-03-29 15:52 UTC, danila19991 commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
@levozavr осознал что это не правильно, твои предложения как это исправлять?

2019-03-29 15:53 UTC, danila19991 commented on documentation/database.md
> +**Analyze** - Список всех проведенных анализов
Результатом анализа является RawData или Link или Property

2019-03-29 15:56 UTC, danila19991 commented
@levozavr а если потом появится 1..n то придется еще раз всю схему переделывать?

2019-03-29 15:56 UTC, levozavr commented on documentation/database.md
> +6. **is_visiable** - Флаг является ли документа общедовступным или частным
@danila19991 стоит обсудить с командой тот момент, который ты предлагал, но чуть позже, когда остальные вопросы решаться, ок?

2019-03-29 15:58 UTC, levozavr commented
@danila19991  это как ?

есть же связи только трех типов:
- 1->n
- 1->1
- n->n

2019-03-29 16:01 UTC, levozavr commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
@danila19991 у тебя стрелки не корректны, у тебя же там стрелка что один анализ может использоваться много раз

2019-03-29 16:03 UTC, danila19991 commented
@levozavr есть связи 4 типов
![image](https://user-images.githubusercontent.com/21951917/55245952-43850680-5255-11e9-844a-fa75702fab6a.png)

2019-03-29 16:06 UTC, levozavr commented on documentation/database.md
> +**Analyze** - Список всех проведенных анализов
@danila19991 спасибо понял, @robot-lab/team-judicial-analysis все согласны с этим?

2019-03-29 16:07 UTC, danila19991 commented on documentation/database.md
> +**AnalyzeData** - Отношение использованных анализов
@levozavr исправил

2019-03-29 16:07 UTC, levozavr commented
@danila19991 0 - nullable поле которое ссылается на эту таблицу?

2019-03-29 16:07 UTC, danila19991 commented
@levozavr да

2019-03-29 16:09 UTC, levozavr commented
@danila19991 но ты же и так пишешь not null поля

2019-03-29 16:09 UTC, levozavr commented
@danila19991 но я согласен, можно оставить и так, лучше скажи что насчет  стрелок

> по поводу исполнения исполнения отношений, можно их изобразить так: от какого поля к какому идет связь

2019-03-29 16:12 UTC, danila19991 commented
@levozavr проверил все стрелки: ромбик у того кто ссылается, стрелочка у тго на которого ссылается

2019-03-29 16:13 UTC, levozavr commented
@danila19991 но я согласен, можно оставить и так, лучше скажи что насчет  стрелок
у тебя в таблицах стрелки идут произвольно, а если их направить от public keys к primary keys

> по поводу исполнения исполнения отношений, можно их изобразить так: от какого поля к какому идет связь

2019-03-29 21:34 UTC, levkovalenko approved these changes

2019-03-30 06:07 UTC, Vasar007 approved these changes
На будущее хочу порекомендовать писать в каком-нибудь редакторе с проверкой орфографии и синтаксиса MarkDown, чтобы не было столько ошибок.

Также для создания ER-диаграмм существуют более удобные инструменты, чем `draw.io`. Если абстрагироваться от конкретных БД, то можно было взять, например, DataGrid от JetBrains или любое расширение к распространённым IDE, работающее с БД. И рисунок получился бы красивее, и проще было его составлять.

2019-03-30 07:51 UTC, merged