Add models by documentation
robot-lab/judyst-backend pull request #9
Opened 2019-03-30 12:43 UTC by danila19991

Add models by documentaion
Closes #3

2019-03-30 16:09 UTC, levozavr commented on core/models.py
> +    owner_key = models.IntegerField(primary_key=True)
может uuid стоит использовать?

2019-03-30 16:20 UTC, levozavr commented on core/models.py
> +    type = models.ForeignKey(DocumentSupertype, on_delete=models.PROTECT)
поля именовать зарезервированными словами не очень...

2019-03-30 16:37 UTC, levkovalenko requested changes
Еще проверь точно ли везде расставлен null для полей

2019-03-30 16:37 UTC, levozavr commented on core/models.py
> +class OrganisationUser(models.Model):
Это связь Many to Many? в django есть встроенные реализации

2019-03-30 16:37 UTC, levozavr commented on core/models.py
> +    pass
не так
```suggestion
    owner_key = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

2019-03-30 16:37 UTC, levozavr commented on core/models.py
> +    pass
и еще import uuid

2019-03-30 16:37 UTC, levozavr commented on core/models.py
> +class LinkPosition(models.Model):
Почему не встроенная many to many?

2019-04-01 20:45 UTC, Rexarrior approved these changes

2019-04-02 05:44 UTC, levkovalenko approved these changes

2019-04-02 07:27 UTC, Vasar007 commented
Почему есть различия?

![image](https://user-images.githubusercontent.com/21951872/55383878-e8436480-5531-11e9-854d-59aaf137bc06.png)
![image](https://user-images.githubusercontent.com/21951872/55383887-eda0af00-5531-11e9-9e12-005a7d94f381.png)

2019-04-02 07:28 UTC, Vasar007 commented
![image](https://user-images.githubusercontent.com/21951872/55383914-0315d900-5532-11e9-95d4-0ef6c1c23023.png)
![image](https://user-images.githubusercontent.com/21951872/55383932-0c9f4100-5532-11e9-8d8f-6a74c12181d1.png)

2019-04-02 07:30 UTC, Vasar007 commented
![image](https://user-images.githubusercontent.com/21951872/55384015-3e180c80-5532-11e9-92c7-ca9710da3001.png)
![image](https://user-images.githubusercontent.com/21951872/55384032-47a17480-5532-11e9-94dc-fef61a0b92eb.png)

2019-04-02 07:30 UTC, Vasar007 commented
Внимательнее с названиями, иначе документация так потеряет всякий смысл

![image](https://user-images.githubusercontent.com/21951872/55384047-5425cd00-5532-11e9-9629-a3da5e8fe1a1.png)
![image](https://user-images.githubusercontent.com/21951872/55384055-58ea8100-5532-11e9-9a6c-e43269de3d19.png)

2019-04-02 07:31 UTC, Vasar007 requested changes
Ответь на вопросы.

2019-04-02 07:49 UTC, danila19991 commented
@Vasar007 

Для пользователя я наследовался от базового пользователя django который содержит дополнительные поля. Наследовался ради встроенных методов защиты пароля и автоматических проверок ключевых полей. 

В таблице owner сменил название поля так как pk зарезервировано на уровне django. 

По поводу OrganisationUser эта таблица генерировалась автоматически, и я не нагал способа сделать primary key при помощи 2 полей(проще поменять нашу документацию)

2019-04-02 07:51 UTC, Vasar007 commented
Так меняй документацию, нужно поддерживать её в актуальном состоянии.

2019-04-02 07:54 UTC, danila19991 commented
Актуализировал ER схему в описании pr

2019-04-02 07:58 UTC, Vasar007 commented
А что поменялось-то? Всё равно не соответствует [database.md](https://github.com/robot-lab/judyst-backend/blob/dev/documentation/database.md).

2019-04-02 08:35 UTC, danila19991 commented
Синхронизировал документацию и реализацию

2019-04-02 12:07 UTC, Vasar007 approved these changes

2019-04-02 12:19 UTC, merged